Bt/Bt/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #/movies/
    path('stylist/', include('stylist.urls')),
    re_path(r'^', include('stylist.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bt/stylist/urls.py
from django.urls import path, include , re_path
from . import views
from django.conf.urls import url

app_name = 'stylist'

urlpatterns = [
  # /movies/
  re_path(r'^$', views.IndexView.as_view(), name = 'index'),

  # /movies/785/
  re_path(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

  url(r'stylist/add/$', views.FreelancerCreate.as_view(), name = 'freelancer_add'),

  url(r'stylist/(?P<pk>[0-9]+)/$', views.FreelancerUpdate.as_view(), name = 'freelancer_update'),

  url(r'stylist/(?P<pk>[0-9]+)/delete/$', views.FreelancerDelete.as_view(), name = 'freelancer_delete'),




]

Bt/stylist/models.py
from django.db import models
from enum import Enum
from django.urls import reverse


class Price(models.Model):
    day_session = models.CharField(max_length=250)
    evening_session = models.CharField(max_length=250)
    morning_session = models.CharField(max_length=250)

    def __str__(self):
        return self.day_session


class Timeslot(models.Model):
    SessionStatus = (
        ('FREE', 'free'),
        ('BUSY', 'busy'),
    )

    day = models.CharField(max_length=250, choices=SessionStatus, default='FREE')
    evening = models.CharField(max_length=250, choices=SessionStatus, default='FREE')
    morning = models.CharField(max_length=250, choices=SessionStatus, default='FREE')

    def __str__(self):
        return self.evening


class Freelancer(models.Model):
    StatusType = (
        ('Stylist', 'Stylist'),
        ('Educator', 'Educator'),
    )

    freelancer_name = models.CharField(max_length=250)
    age = models.IntegerField()
    value = models.IntegerField()
    type = models.CharField(max_length=250, choices=StatusType, default='Stylist')
    time_slot_id = models.ForeignKey(Timeslot, on_delete=models.CASCADE)
    image = models.FileField()

    def get_absolute_url(self):
        return reverse('stylist:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.freelancer_name

Bt/stylist/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Freelancer


class IndexView(generic.ListView):
    template_name = 'stylist/index.html'
    context_object_name = 'All_Freelancer'

    def get_queryset(self):
        return Freelancer.objects.all()


class DetailView(generic.DetailView):
    model = Freelancer
    template_name = 'stylist/detail.html'


class FreelancerCreate(CreateView):
    model = Freelancer
    fields = ['freelancer_name', 'age', 'value', 'type', 'time_slot_id', 'image']


class FreelancerUpdate(UpdateView):
    model = Freelancer
    fields = ['freelancer_name', 'age', 'value', 'type', 'time_slot_id', 'image']


class FreelancerDelete(DeleteView):
    model = Freelancer
    success_url = reverse_lazy('stylist:index')

Bt/stylist/templates/stylist/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %} BeautyTown {% endblock %}</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<!-- my work -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type ="text/css" href="{% static 'music/style.css' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Allan' rel='stylesheet'>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- my work -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid" >
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collaps" data-target="#topNavBar">

                <span class="icon-bar" ></span>

            </button>
            <a class="navbar-brand" href="{% url 'stylist:index'%}">BeautyTown.com</a>
        </div>
<!-- my work -->

        <ul class="nav nav-pills">
            <li>
                <a href="index.html">
                    <span class="glyphicon glyphicon-home"></span> Home
                 </a>
            </li>
            <li>
                <a href="log_in.html">
                    <span class="glyphicon glyphicon"></span> Log-in
                </a>
            </li>
            <li>
                <a href="sign_in.html">
                    <span class="glyphicon glyphicon"></span> Sign-in
                </a>
            </li>
            <li>
                <a href="{% url 'stylist:freelancer_add' %}">
                    <span class="glyphicon glyphicon-info-sign"></span> Add
                </a>
            </li>
        </ul>


<!-- my work -->

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class ="active">
                    <a href="{% url 'stylist:index'%}">

                        <span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp;
                        Talents
                    </a>

                </li>

                <li class ="">
                    <a href="{% url 'stylist:index'%}">

                        <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>&nbsp;
                        Jobbs
                    </a>

                </li>

            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="/action_page.php">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">

                </div>
                <button class="btn btn-default" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
            </form>
        </div>
    </div>
</nav>
    {% block body %}
    {% endblock %}

</body>
</html>

Bt/stylist/templates/stylist/detail.html
{% extends "stylist/base.html" %}
{% block title %} Stylist details {% endblock %}

{% block body %}

    <h1> hear is the details of the {{ freelancer.freelancer_name }} freelancer </h1>

    <img src="{{ freelancer.image.url}}" alt="Stylist face" height="420" width="420">

    <h2>{{ freelancer.age }}</h2>

    <div class="col-lg-4">
          <h1>Business Name or Tagline</h1>
          <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
          <a class="btn btn-primary btn-lg" href="{% url 'stylist:freelancer_delete' freelancer.id %}">delete</a>
            <a class="btn btn-primary btn-lg" href="{% url 'stylist:freelancer_update' freelancer.id %}">modify</a>
    </div>

{% endblock %}

Bt/stylist/templates/stylist/form-template.html
{% for field in form%}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small"> {{ field.errors }}</span>
        </div>
        <lable class="control-label col-sm-2">{{ field.label_tag }}</lable>
        <div class="col-sm-10"> {{ field }} </div>

    </div>


{% endfor %}

Bt/stylist/templates/stylist/freelancer_form.html
{% extends "stylist/base.html" %}
{% block title %} Stylist details {% endblock %}

{% block body %}
<div class="container-fluid">

    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        {% include 'stylist/form-template.html'%}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success"> Submit</button>
            </div>
        </div>

    </form>


</div>





{% endblock %}

Bt/stylist/templates/stylist/index.html
{% extends 'stylist/base.html' %}

{% block title %} Stylist {% endblock %}

{% block body %}

    <h1> hear is the details of the Freelancers </h1>

    {% if All_Freelancer %}

        <ul>
            {% for style in All_Freelancer %}
                <div class="col-lg-4 col-sm-6 text-center mb-4">
                    <img class="rounded-circle img-fluid d-block mx-auto" src="{{style.image.url}}" alt="Stylist face" height="200" width="200">
                        <h3>
                            <a href="{% url 'stylist:detail' style.id %}">{{style.freelancer_name}}.</a>
                        </h3>
                        <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
                </div>


            {% endfor %}

        </ul>


    {% else %}
        <h3>you don't have any movies</h3>

    {% endif %}

{% endblock %}